export const APP_TITLE = "Greenwich Blog"
const API = "http://localhost:8000/api"
export const API_PROJECT = `${API}/project`
export const API_CAMPUS = `${API}/campus`
export const API_UPLOAD = `${API}/uploads`
export const API_FACULTY= `${API}/faculty`
export const API_TEACHER= `${API}/teacher`
export const API_STUDENT= `${API}/student`
export const API_ACCOUNT = `${API}/user`
export const API_IMAGE = "http://localhost:8000/uploads"